# This is a basic workflow to help you get started with Actions

name: On PR Submit

# Control when the action will run. 
on:
  # Trigger the workflow on push event
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - 'docs/**'
      - 'extra/**'
      - '**.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 13

    # Skip based on commit message
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.1


      # Build --- TODO: add yarn build:docs once this succeeds
      - run: |
            yarn && yarn build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
